### ISSUE TITLE
Embedding storybook breaking the UI in certain aspects

### ISSUE THREAD

**Issue by monetree** [loopsocial/react-fwn#12]
**Here is my react code.**

```
            import ReactFWN from 'react-fwn'

            <ReactFWN
              app_id="I9Agp--RrYDpRmMXqH498a3e0kxmaJSZ"
              mode="story"
              open_in="default"
              autoplay
              open_in={"_iframe"}
              max_videos={1}
              placement="middle"
              size="large"
              />
```

<img width="1440" alt="Screenshot 2021-03-30 at 1 06 32 PM" src="https://user-images.githubusercontent.com/38796292/112951329-dadd0700-9158-11eb-95f4-9612dc863068.png">

Please refer to the above image. And it is coming fine for the first time.
We are displaying the storybook inside our product feeds.

But, when i scroll down and new product appending to the array it is breaking.
We have an array where first time 5 products there.

As we have infinity scroll for product feeds when user scrolls down we are updating the array and appending 5 more products to the array. So that time component rerenders.

There the problem comes.

<img width="1440" alt="Screenshot 2021-03-30 at 1 12 07 PM" src="https://user-images.githubusercontent.com/38796292/112951991-9a31bd80-9159-11eb-82de-4c68495fe4cc.png">

Now. Please refer above image. Here the storybook completely breaking when i scroll down.

Please take a look and give some feedback how we can solve this to overcome our business problems.

**Comment by pista329** [comment]
Hi @monetree, Thank you for trying out our React component. I would suggest to experiment with wrapping element display and width, for example..

```html
<div style={{display: 'block', width: '100%'}}>
   <ReactFWN ... />
</div>
```

**Comment by monetree** [comment]
```
            <div style={{ display:'block', width: '100%' }}>
            <ReactFWN
              app_id="I9Agp--RrYDpRmMXqH498a3e0kxmaJSZ"
              mode="story"
              open_in="default"
              autoplay
              open_in={"_iframe"}
              max_videos={1}
              placement="middle"
              size="large"
              />
          </div>
```


<img width="1440" alt="Screenshot 2021-03-31 at 12 31 30 AM" src="https://user-images.githubusercontent.com/38796292/113042223-8cf7eb80-91b8-11eb-83d6-5b0b60448804.png">


I did same but, still not working. Coming multiple. Tried experimenting a lot

**Comment by pista329** [comment]
@monetree Would you please update for the latest version. Storyblock support (mode=story) was just added by https://github.com/loopsocial/react-fwn/pull/14

`npm install --save react-fwn@latest`
